title: <b>Harry<b> | Yunlong Wang # your name (or website title) here
logo: "/images/1322530626.jpg" # your photo (or logo) here ?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Aspiring Data Analyst/Scientist</b>
  <br><br>
  Dad/Cook/Gardener 
  <br><br>
  <a href="https://www.linkedin.com/in/harrywangmarshall/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
