title: Harry Wang # your name (or website title) here
logo: "/images/1322530626.jpg" # your photo (or logo) here ?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Aspiring Data Analyst/Scientist</b>
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/harrywangmarshall/">View My LinkedIn Profile</a> 
  <i class="fab fa-linkedin"></i>
  <a href="https://www.linkedin.com/in/harrywangmarshall/" class="social-icon si-rounded si-small si-linkedin">
    <i class="icon-linkedin"></i>
    <i class="icon-linkedin"></i>
 </a>
 <div id="idLinkedInIcon" onclick="window.open('https://www.linkedin.com/sharing/share-offsite/?url=https://www.google.com');" style="background-color:rgb(0, 102, 170);border-radius:6px;color:white;cursor:pointer;display:inline-block;font:bold 35px Arial, Helvetica, sans-serif;height:40px;margin-top:1px;text-align:center;width:40px;">in</div>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
